name: Vela IPTV
options:
  bundleIdPrefix: com.velaiptv
  deploymentTarget:
    macOS: "15.0"
  defaultConfig: Debug
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    ENABLE_HARDENED_RUNTIME: YES
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    PRODUCT_BUNDLE_IDENTIFIER: com.velaiptv.app

targets:
  Vela:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: Vela
        excludes:
          - "**/*.md"
          - "**/Info.plist"
          - "**/*.entitlements"
    info:
      path: Info.plist
      properties:
        CFBundleName: Vela IPTV
        CFBundleDisplayName: Vela IPTV
        CFBundleIdentifier: com.velaiptv.app
        CFBundleVersion: "3"
        CFBundleShortVersionString: "1.0.3"
        CFBundleIconFile: AppIcon
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        LSMinimumSystemVersion: "15.0"
        NSPrincipalClass: NSApplication
        SUFeedURL: "https://jacksonf-netizen.github.io/Vela-IPTV/appcast.xml"
        SUPublicEDKey: "f1upqhkOxe1bU7kzjvWl9iNZWEvlmDCSu2xwbi9hrVo="
    entitlements:
      path: VelaIPTV.entitlements
      properties:
        com.apple.security.network.client: true
    settings:
      base:
        PRODUCT_NAME: Vela IPTV
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        ENABLE_USER_SCRIPT_SANDBOXING: NO
